import { Badge } from "@/components/ui/badge"
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"

function Main() {
    const bio = `I’m a second-year Computer Science student focused on software development and web technologies.I work mainly with Python and JavaScript, building web applications with an emphasis on clear structure, maintainability, and correctness.

    I have experience across the full web stack, including backend logic, templating, and frontend behavior, and I’m comfortable working with common development tools and workflows. I follow Agile/Scrum practices and apply DevOps principles such as version control, incremental delivery, and environment-aware development.

    My background includes several years of professional experience outside of computer science, which has shaped a practical, disciplined approach to problem-solving. I value writing understandable code, reasoning about trade-offs, and improving systems through iteration rather than shortcuts.
    
    This text was generated by AI because who types anything anymore am i right?
    
    `

  return (
    <div className="flex flex-col md:flex-row gap-4 justify-center px-4 pt-4">
    <Card className="relative w-full max-w-xl">
      <CardHeader>
        <CardTitle>
          <h1 className="text-5xl md:text-3xl font-bold">BIO</h1>
        </CardTitle>
      </CardHeader>
      <CardContent>
        <CardDescription className="whitespace-pre-line">
            {bio}
        </CardDescription>
        </CardContent>
        <CardContent>
            <h1 className="text-5xl md:text-3xl font-bold">SKILLS</h1>
        </CardContent>
        <CardContent>

            <div className="flex w-full flex-wrap justify-left gap-2">
            <Badge variant="outline">Python</Badge>
            <Badge variant="outline">JavaScript</Badge>
            <Badge variant="outline">SQL</Badge>
            <Badge variant="outline">Robot Framework</Badge>
            <Badge variant="outline">Tailwind CSS</Badge>
            <Badge variant="outline">Playwright</Badge>
            <Badge variant="outline">Scrum</Badge>
            <Badge variant="outline">DevOps</Badge>
            <Badge variant="outline">Frontend</Badge>
            <Badge variant="outline">Backend</Badge>
            <Badge variant="outline">git</Badge>
            </div>
        </CardContent>
    </Card>
    <Card className="relative w-full max-w-sm pt-2">
      <div className="absolute inset-0 z-30 aspect-square bg-black/35" />
      <img
        src="./src/photos/my-photo.png"
        alt="Event cover"
        className="relative z-40 aspect-square w-full object-cover brightness-60 grayscale dark:brightness-40"
      />
      <CardHeader>
        <CardTitle>That's me</CardTitle>
        <CardDescription>
          and probably the best photo of me.
        </CardDescription>
      </CardHeader>
    </Card>
    </div>
  )
}

export default Main;